// Generated by gencpp from file jrc_srvs/smooth.msg
// DO NOT EDIT!


#ifndef JRC_SRVS_MESSAGE_SMOOTH_H
#define JRC_SRVS_MESSAGE_SMOOTH_H

#include <ros/service_traits.h>


#include <jrc_srvs/smoothRequest.h>
#include <jrc_srvs/smoothResponse.h>


namespace jrc_srvs
{

struct smooth
{

typedef smoothRequest Request;
typedef smoothResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct smooth
} // namespace jrc_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jrc_srvs::smooth > {
  static const char* value()
  {
    return "7f92d35d2c82d2a4c46ca92d3433aa56";
  }

  static const char* value(const ::jrc_srvs::smooth&) { return value(); }
};

template<>
struct DataType< ::jrc_srvs::smooth > {
  static const char* value()
  {
    return "jrc_srvs/smooth";
  }

  static const char* value(const ::jrc_srvs::smooth&) { return value(); }
};


// service_traits::MD5Sum< ::jrc_srvs::smoothRequest> should match 
// service_traits::MD5Sum< ::jrc_srvs::smooth > 
template<>
struct MD5Sum< ::jrc_srvs::smoothRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jrc_srvs::smooth >::value();
  }
  static const char* value(const ::jrc_srvs::smoothRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jrc_srvs::smoothRequest> should match 
// service_traits::DataType< ::jrc_srvs::smooth > 
template<>
struct DataType< ::jrc_srvs::smoothRequest>
{
  static const char* value()
  {
    return DataType< ::jrc_srvs::smooth >::value();
  }
  static const char* value(const ::jrc_srvs::smoothRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jrc_srvs::smoothResponse> should match 
// service_traits::MD5Sum< ::jrc_srvs::smooth > 
template<>
struct MD5Sum< ::jrc_srvs::smoothResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jrc_srvs::smooth >::value();
  }
  static const char* value(const ::jrc_srvs::smoothResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jrc_srvs::smoothResponse> should match 
// service_traits::DataType< ::jrc_srvs::smooth > 
template<>
struct DataType< ::jrc_srvs::smoothResponse>
{
  static const char* value()
  {
    return DataType< ::jrc_srvs::smooth >::value();
  }
  static const char* value(const ::jrc_srvs::smoothResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JRC_SRVS_MESSAGE_SMOOTH_H
