// Generated by gencpp from file jrc_srvs/smooth_multiResponse.msg
// DO NOT EDIT!


#ifndef JRC_SRVS_MESSAGE_SMOOTH_MULTIRESPONSE_H
#define JRC_SRVS_MESSAGE_SMOOTH_MULTIRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jrc_srvs
{
template <class ContainerAllocator>
struct smooth_multiResponse_
{
  typedef smooth_multiResponse_<ContainerAllocator> Type;

  smooth_multiResponse_()
    : mark_multi()  {
    }
  smooth_multiResponse_(const ContainerAllocator& _alloc)
    : mark_multi(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _mark_multi_type;
  _mark_multi_type mark_multi;





  typedef boost::shared_ptr< ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> const> ConstPtr;

}; // struct smooth_multiResponse_

typedef ::jrc_srvs::smooth_multiResponse_<std::allocator<void> > smooth_multiResponse;

typedef boost::shared_ptr< ::jrc_srvs::smooth_multiResponse > smooth_multiResponsePtr;
typedef boost::shared_ptr< ::jrc_srvs::smooth_multiResponse const> smooth_multiResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jrc_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68760c887143af51a7ea43710a80f059";
  }

  static const char* value(const ::jrc_srvs::smooth_multiResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68760c887143af51ULL;
  static const uint64_t static_value2 = 0xa7ea43710a80f059ULL;
};

template<class ContainerAllocator>
struct DataType< ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jrc_srvs/smooth_multiResponse";
  }

  static const char* value(const ::jrc_srvs::smooth_multiResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] mark_multi\n\
\n\
";
  }

  static const char* value(const ::jrc_srvs::smooth_multiResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mark_multi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct smooth_multiResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jrc_srvs::smooth_multiResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jrc_srvs::smooth_multiResponse_<ContainerAllocator>& v)
  {
    s << indent << "mark_multi[]" << std::endl;
    for (size_t i = 0; i < v.mark_multi.size(); ++i)
    {
      s << indent << "  mark_multi[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.mark_multi[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JRC_SRVS_MESSAGE_SMOOTH_MULTIRESPONSE_H
