// Generated by gencpp from file jrc_srvs/smoothRequest.msg
// DO NOT EDIT!


#ifndef JRC_SRVS_MESSAGE_SMOOTHREQUEST_H
#define JRC_SRVS_MESSAGE_SMOOTHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jrc_srvs
{
template <class ContainerAllocator>
struct smoothRequest_
{
  typedef smoothRequest_<ContainerAllocator> Type;

  smoothRequest_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , status(0.0)  {
    }
  smoothRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , status(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;

   typedef double _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::jrc_srvs::smoothRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jrc_srvs::smoothRequest_<ContainerAllocator> const> ConstPtr;

}; // struct smoothRequest_

typedef ::jrc_srvs::smoothRequest_<std::allocator<void> > smoothRequest;

typedef boost::shared_ptr< ::jrc_srvs::smoothRequest > smoothRequestPtr;
typedef boost::shared_ptr< ::jrc_srvs::smoothRequest const> smoothRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jrc_srvs::smoothRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jrc_srvs::smoothRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jrc_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jrc_srvs::smoothRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jrc_srvs::smoothRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jrc_srvs::smoothRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jrc_srvs::smoothRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jrc_srvs::smoothRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jrc_srvs::smoothRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jrc_srvs::smoothRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb1b5618c05b200c2f2dd59b84133592";
  }

  static const char* value(const ::jrc_srvs::smoothRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb1b5618c05b200cULL;
  static const uint64_t static_value2 = 0x2f2dd59b84133592ULL;
};

template<class ContainerAllocator>
struct DataType< ::jrc_srvs::smoothRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jrc_srvs/smoothRequest";
  }

  static const char* value(const ::jrc_srvs::smoothRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jrc_srvs::smoothRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 theta\n\
float64 status\n\
";
  }

  static const char* value(const ::jrc_srvs::smoothRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jrc_srvs::smoothRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct smoothRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jrc_srvs::smoothRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jrc_srvs::smoothRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "status: ";
    Printer<double>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JRC_SRVS_MESSAGE_SMOOTHREQUEST_H
