(cl:defpackage velocity_smooth-srv
  (:use )
  (:export
   "SMOOTH_SRV"
   "<SMOOTH_SRV-REQUEST>"
   "SMOOTH_SRV-REQUEST"
   "<SMOOTH_SRV-RESPONSE>"
   "SMOOTH_SRV-RESPONSE"
   "SMOOTH_SRV_MULTI"
   "<SMOOTH_SRV_MULTI-REQUEST>"
   "SMOOTH_SRV_MULTI-REQUEST"
   "<SMOOTH_SRV_MULTI-RESPONSE>"
   "SMOOTH_SRV_MULTI-RESPONSE"
  ))

