// Generated by gencpp from file velocity_smooth/smooth_srv.msg
// DO NOT EDIT!


#ifndef VELOCITY_SMOOTH_MESSAGE_SMOOTH_SRV_H
#define VELOCITY_SMOOTH_MESSAGE_SMOOTH_SRV_H

#include <ros/service_traits.h>


#include <velocity_smooth/smooth_srvRequest.h>
#include <velocity_smooth/smooth_srvResponse.h>


namespace velocity_smooth
{

struct smooth_srv
{

typedef smooth_srvRequest Request;
typedef smooth_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct smooth_srv
} // namespace velocity_smooth


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::velocity_smooth::smooth_srv > {
  static const char* value()
  {
    return "7f92d35d2c82d2a4c46ca92d3433aa56";
  }

  static const char* value(const ::velocity_smooth::smooth_srv&) { return value(); }
};

template<>
struct DataType< ::velocity_smooth::smooth_srv > {
  static const char* value()
  {
    return "velocity_smooth/smooth_srv";
  }

  static const char* value(const ::velocity_smooth::smooth_srv&) { return value(); }
};


// service_traits::MD5Sum< ::velocity_smooth::smooth_srvRequest> should match 
// service_traits::MD5Sum< ::velocity_smooth::smooth_srv > 
template<>
struct MD5Sum< ::velocity_smooth::smooth_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::velocity_smooth::smooth_srv >::value();
  }
  static const char* value(const ::velocity_smooth::smooth_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::velocity_smooth::smooth_srvRequest> should match 
// service_traits::DataType< ::velocity_smooth::smooth_srv > 
template<>
struct DataType< ::velocity_smooth::smooth_srvRequest>
{
  static const char* value()
  {
    return DataType< ::velocity_smooth::smooth_srv >::value();
  }
  static const char* value(const ::velocity_smooth::smooth_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::velocity_smooth::smooth_srvResponse> should match 
// service_traits::MD5Sum< ::velocity_smooth::smooth_srv > 
template<>
struct MD5Sum< ::velocity_smooth::smooth_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::velocity_smooth::smooth_srv >::value();
  }
  static const char* value(const ::velocity_smooth::smooth_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::velocity_smooth::smooth_srvResponse> should match 
// service_traits::DataType< ::velocity_smooth::smooth_srv > 
template<>
struct DataType< ::velocity_smooth::smooth_srvResponse>
{
  static const char* value()
  {
    return DataType< ::velocity_smooth::smooth_srv >::value();
  }
  static const char* value(const ::velocity_smooth::smooth_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VELOCITY_SMOOTH_MESSAGE_SMOOTH_SRV_H
