// Generated by gencpp from file velocity_smooth/smooth_srv_multi.msg
// DO NOT EDIT!


#ifndef VELOCITY_SMOOTH_MESSAGE_SMOOTH_SRV_MULTI_H
#define VELOCITY_SMOOTH_MESSAGE_SMOOTH_SRV_MULTI_H

#include <ros/service_traits.h>


#include <velocity_smooth/smooth_srv_multiRequest.h>
#include <velocity_smooth/smooth_srv_multiResponse.h>


namespace velocity_smooth
{

struct smooth_srv_multi
{

typedef smooth_srv_multiRequest Request;
typedef smooth_srv_multiResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct smooth_srv_multi
} // namespace velocity_smooth


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::velocity_smooth::smooth_srv_multi > {
  static const char* value()
  {
    return "3b1e979c6d58d1f5eaa86cabfb1c7458";
  }

  static const char* value(const ::velocity_smooth::smooth_srv_multi&) { return value(); }
};

template<>
struct DataType< ::velocity_smooth::smooth_srv_multi > {
  static const char* value()
  {
    return "velocity_smooth/smooth_srv_multi";
  }

  static const char* value(const ::velocity_smooth::smooth_srv_multi&) { return value(); }
};


// service_traits::MD5Sum< ::velocity_smooth::smooth_srv_multiRequest> should match 
// service_traits::MD5Sum< ::velocity_smooth::smooth_srv_multi > 
template<>
struct MD5Sum< ::velocity_smooth::smooth_srv_multiRequest>
{
  static const char* value()
  {
    return MD5Sum< ::velocity_smooth::smooth_srv_multi >::value();
  }
  static const char* value(const ::velocity_smooth::smooth_srv_multiRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::velocity_smooth::smooth_srv_multiRequest> should match 
// service_traits::DataType< ::velocity_smooth::smooth_srv_multi > 
template<>
struct DataType< ::velocity_smooth::smooth_srv_multiRequest>
{
  static const char* value()
  {
    return DataType< ::velocity_smooth::smooth_srv_multi >::value();
  }
  static const char* value(const ::velocity_smooth::smooth_srv_multiRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::velocity_smooth::smooth_srv_multiResponse> should match 
// service_traits::MD5Sum< ::velocity_smooth::smooth_srv_multi > 
template<>
struct MD5Sum< ::velocity_smooth::smooth_srv_multiResponse>
{
  static const char* value()
  {
    return MD5Sum< ::velocity_smooth::smooth_srv_multi >::value();
  }
  static const char* value(const ::velocity_smooth::smooth_srv_multiResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::velocity_smooth::smooth_srv_multiResponse> should match 
// service_traits::DataType< ::velocity_smooth::smooth_srv_multi > 
template<>
struct DataType< ::velocity_smooth::smooth_srv_multiResponse>
{
  static const char* value()
  {
    return DataType< ::velocity_smooth::smooth_srv_multi >::value();
  }
  static const char* value(const ::velocity_smooth::smooth_srv_multiResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VELOCITY_SMOOTH_MESSAGE_SMOOTH_SRV_MULTI_H
