// Generated by gencpp from file move_forward/Jrc_move.msg
// DO NOT EDIT!


#ifndef MOVE_FORWARD_MESSAGE_JRC_MOVE_H
#define MOVE_FORWARD_MESSAGE_JRC_MOVE_H

#include <ros/service_traits.h>


#include <move_forward/Jrc_moveRequest.h>
#include <move_forward/Jrc_moveResponse.h>


namespace move_forward
{

struct Jrc_move
{

typedef Jrc_moveRequest Request;
typedef Jrc_moveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Jrc_move
} // namespace move_forward


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_forward::Jrc_move > {
  static const char* value()
  {
    return "5f282b47bb61e9d36bb6017105afa68a";
  }

  static const char* value(const ::move_forward::Jrc_move&) { return value(); }
};

template<>
struct DataType< ::move_forward::Jrc_move > {
  static const char* value()
  {
    return "move_forward/Jrc_move";
  }

  static const char* value(const ::move_forward::Jrc_move&) { return value(); }
};


// service_traits::MD5Sum< ::move_forward::Jrc_moveRequest> should match 
// service_traits::MD5Sum< ::move_forward::Jrc_move > 
template<>
struct MD5Sum< ::move_forward::Jrc_moveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_forward::Jrc_move >::value();
  }
  static const char* value(const ::move_forward::Jrc_moveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_forward::Jrc_moveRequest> should match 
// service_traits::DataType< ::move_forward::Jrc_move > 
template<>
struct DataType< ::move_forward::Jrc_moveRequest>
{
  static const char* value()
  {
    return DataType< ::move_forward::Jrc_move >::value();
  }
  static const char* value(const ::move_forward::Jrc_moveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_forward::Jrc_moveResponse> should match 
// service_traits::MD5Sum< ::move_forward::Jrc_move > 
template<>
struct MD5Sum< ::move_forward::Jrc_moveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_forward::Jrc_move >::value();
  }
  static const char* value(const ::move_forward::Jrc_moveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_forward::Jrc_moveResponse> should match 
// service_traits::DataType< ::move_forward::Jrc_move > 
template<>
struct DataType< ::move_forward::Jrc_moveResponse>
{
  static const char* value()
  {
    return DataType< ::move_forward::Jrc_move >::value();
  }
  static const char* value(const ::move_forward::Jrc_moveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_FORWARD_MESSAGE_JRC_MOVE_H
